services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://admin:password@mongodb:27017/url-shortener?authSource=admin
      - CORS_ORIGIN=http://localhost # For browser requests

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      # Use localhost for browser API calls, backend for container-to-container
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend

volumes:
  mongodb_data:
